apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scraper.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scraper.labels" . | nindent 4 }}
data:
  {{- with .Values.config.data }}
  config.yaml: |
  {{- toYaml . | nindent 4 }}
  {{- end }}
