apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "scraper.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scraper.labels" . | nindent 4 }}
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
          {{- with .Values.cronjob.podAnnotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
          {{- end }}
        spec:
          serviceAccountName: {{ include "scraper.fullname" . }}
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.scraper.image.repository }}:{{ .Values.scraper.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.scraper.image.pullPolicy }}
              env:
                - name: NODE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
                - name: NAMESPACE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: NEW_RELIC_ACCOUNT_ID
                  value:  "{{ .Values.scraper.config.newrelic.accountId }}"
                - name: NEW_RELIC_LICENSE_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "scraper.fullname" . }}
                      key: licenseKey
                      optional: false
                - name: CONFIG_PATH
                  value: "{{ .Values.scraper.mountPathConfig }}/config.yaml"
              volumeMounts:
                - name: config
                  mountPath: {{ .Values.scraper.mountPathConfig }}
          restartPolicy: {{ .Values.cronjob.restartPolicy }}
          volumes:
            - name: config
              configMap:
                name: {{ include "scraper.fullname" . }}
                optional: false
          {{- with .Values.cronjob.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 14 }}
          {{- end }}
          {{- with .Values.cronjob.affinity }}
          affinity:
            {{- toYaml . | nindent 14 }}
          {{- end }}
          {{- with .Values.cronjob.tolerations }}
          tolerations:
            {{- toYaml . | nindent 14 }}
          {{- end }}
