apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "scraper.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scraper.labels" . | nindent 4 }}
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
          {{- with .Values.podAnnotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
          {{- end }}
        spec:
          serviceAccountName: {{ include "scraper.fullname" . }}
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                - name: CONFIG_PATH
                  value: "{{ .Values.config.mountPath }}/config.yaml"
              volumeMounts:
                - name: config
                  mountPath: {{ .Values.config.mountPath }}
          restartPolicy: {{ .Values.restartPolicy }}
          volumes:
            - name: config
              configMap:
                name: {{ include "scraper.fullname" . }}
                optional: false
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 14 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 14 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 14 }}
          {{- end }}
