apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scraper.fullname" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  licenseKey: {{ .Values.config.data.newrelic.licenseKey | b64enc }}
